#+TITLE: O site agora é gerado por meio de uma Makefile
#+DATE: <2025-05-17>

Eu considero isso uma evolução ao script que eu estava utilizando.

Essa Makefile não só é menor, como também é mais eficiênte no que faz. É como
dizem, menos é mais.

A Makefile é tão pequena que eu posso colocar ela por inteiro aqui:

#+begin_src makefile
LANG="pt-br"
TITLE="O site do Tukain"
DESCRIPTION="Sou alguém que busca por músicas que me relaxam ou que dão adrenalina… Só depende do dia. Sinta-se livre para explorar o meu espaço neste vasto mundo chamado internet!"
NOTE="Usuário Linux / Blogger / Curioso por tecnología"
SITE_BASENAME="tukain.xyz"
EDITOR="nvim"

all: public

new: posts
	@${EDITOR} posts/$$(date "+%Y-%m-%d_%T").md

index: item
	@cat header > tmp/index.html
	@echo "<center><hgroup><h1 class=\"title\">${TITLE}</h1>" >> tmp/index.html
	@echo "<p class=\"note\">${NOTE}</p></hgroup></center>" >> tmp/index.html
	@echo "<article><p class=\"description\">${DESCRIPTION}</p><hr>" >> tmp/index.html
	@echo "<table><thead><tr><th>Posts ($$(ls -1 ./posts | wc -l))</th></tr></thead><tbody>" >> tmp/index.html
	@for FILE in $$(ls ./posts | sort -r); do \
		echo "<tr><td><a href='/$$(echo $${FILE} | tr -d '.md')'>$$(cat posts/$${FILE} | head -n1 | tr -d \"#\")</a></td></tr>" >> tmp/index.html;\
	done
	@echo "</tbody></table>" >> tmp/index.html
	@cat footer >> tmp/index.html

header:
	@echo "<!DOCTYPE html><html><head><meta http-equiv='Content-Type' content='text/html; charset=UTF-8' /><meta http-equiv='Content-Language' content='${LANG}' /><meta name='generator' content='A freaking Makefile' /><meta name='author' content='tukain' /><meta name='description' content='${DESCRIPTION}' /><meta name='viewport' content='width=device-width, initial-scale=1'><link rel='icon' href='https://avatars.githubusercontent.com/u/205941290' type='image/png' /><link href='/styles.css' rel='stylesheet'><title>${TITLE}</title></head><body>" > header

footer:
	@echo '</body></html>' >> footer

item: header footer
	@if [ -e "tmp" ]; then\
		rm -rf tmp;\
	fi
	@mkdir -p tmp
	@for FILE in $$(ls ./posts | sort -r); do \
		mkdir tmp/$$(echo $$FILE | tr -d '.md');\
		cat header > tmp/$$(echo $$FILE | tr -d '.md')/index.html;\
		echo "<center><h1><a href='/'>${TITLE}</a></h1></center>" >> tmp/$$(echo $$FILE | tr -d '.md')/index.html;\
		echo "<article>" >> tmp/$$(echo $$FILE | tr -d '.md')/index.html;\
		echo "<time>$$(echo $${FILE} | tr '-' '/' | tr '_' ' ' | tr -d '.md')</time>" >> tmp/$$(echo $$FILE | tr -d '.md')/index.html;\
		smu ./posts/$$FILE >> tmp/$$(echo $$FILE | tr -d '.md')/index.html; \
		echo "</article>" >> tmp/$$(echo $$FILE | tr -d '.md')/index.html;\
		cat footer >> tmp/$$(echo $$FILE | tr -d '.md')/index.html;\
	done

feed: item
	@echo '<?xml version="1.0" encoding="UTF-8" ?>' > feed.xml
	@echo '<rss version="2.0">' >> feed.xml
	@echo '<channel>' >> feed.xml
	@echo '<title>${TITLE} - Feed</title>' >> feed.xml
	@echo '<description>Feed do meu blog</description>' >> feed.xml
	@for PAGE in $$(/bin/ls ./posts | sort -r | tr '\n' ' '); do \
	  echo "<item>" >> feed.xml;\
	  echo "<title>$$(smu ./posts/$$PAGE | grep '<h1>' | tr '<>/' '\n' | head -n3 | tail -n1 )</title>" >> feed.xml;\
	  echo "<link>https://${SITE_BASENAME}/$$PAGE</link>" >> feed.xml;\
	  echo "<description><![CDATA[" >> feed.xml;\
	  smu ./posts/$$PAGE >> feed.xml;\
	  echo "]]></description>" >> feed.xml;\
	  echo "</item>" >> feed.xml;\
	done
	@echo '</channel>' >> feed.xml
	@echo '</rss>' >> feed.xml

public: posts assets index feed
	@if [ -e "public" ]; then\
		rm -rf public header footer;\
	fi
	@mkdir -p public
	@cp -r tmp/* assets/* *.xml public
#+end_src
    


Só para fins de comparação, o script tinha exatas 167 linhas, essa Makefile tem
71 linhas. É, dá pra reduzir bastante coisa se você remover as partes
desnecessárias.

Além disso, como já é possível de se ver no topo da Makefile, ela mesma cuida da parte de criação
de novos posts (no passo =new:=). Sendo assim, eu só preciso me preocupar com a criação de conteúdo!

Ainda estou trabalhando nela, quero deixar ela o mais modular que eu conseguir (o que no caso seria
só permitir uma mudança fácil de certos parâmetros), porque planejo deixa-la em um repositório aparte,
com um =README= e uma documentação simples explicando como ela funciona.
