#+TITLE: Estou usando o ox-publish mais uma vez.
#+DESCRIPTION: Depois de pensar bastante, eu decidi que voltarei à escrever esse blog usando o Emacs + ox-publish.
#+DATE: <2025-05-20 ter>

Depois de pensar bastante, eu decidi que voltarei à escrever esse blog usando o Emacs + ox-publish.

É, eu não sei o que eu quero fazer mais com esse site. Ultimamente eu só fico experimentando coisas,
uma atrás da outra, sem muita noção de objetivo. Acabou que agora o site está novamente (pela 4ª vez)
sendo escrito usando o famoso org-mode do Emacs. Só porquê eu voltei a ficar interessado no Emacs.

Bom, o site é meu afinal de contas não é? Posso deixar o meu pseudo-autismo aflorar como bem entender.

Ainda estou reaprendendo a usar o Emacs e o org-mode, mas acredito que isso vá durar pouco tempo.
Eu ainda tenho uma memória muscular quando se trata de navegação, por exemplo, e ainda assim,
não é difícil pesquisar como que se faz X coisa, ou melhor, sair apertando botões e ver o que o
=which-key= vai mostrar o que eu posso fazer.

A minha configuração do Emacs também está sendo atualizada aos poucos, mas mesmo com menos plugins que o
meu Neovim, ela já está no mesmo patamar em relação à funcionalidades.

Na verdade, essa configuração já supera o Neovim, só pelo fato de ser uma configuração do Emacs.
É até injusto comparar os dois, porque é simplesmente desleal comparar um editor de texto com um
sistema de desenvolvimento inteiro.

Enfim, já vou indo.
