url: https://tukain.xyz/
title: Ventriloquo
author: "ventriloquo"
description:
  Um blog simples, feito utilizando o Jekyll.

defaults:
  -
    scope:
      path: ""
    values:
      layout: "base"
  -
    scope:
      path: "_posts"
    values:
      layout: "post"
      category: "blog"
  - scope:
      path: "_drafts"
    values:
      layout: "post"
