title: Ventriloquo
description: >- # this means to ignore newlines until "baseurl:"
  Um pequeno blog onde eu ponho pensamentos meus e coisas do meu cotidiano.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
author:
  name: Ventriloquo
  email: "persona.umpire392@passinbox.com"
  github_username: ventriloquo

# Build settings
theme: "minima"

minima:
  skin: solarized
  show_excerpts: true
  nav_pages:
    - search.md
    - tags.md
    - about.md
  social_links:
    - title: Meu Github
      icon: github
      url: "https://github.com/ventriloquo"
    - title: Minha coleção de músicas
      icon: bandcamp
      url: "https://bandcamp.com/ventriloquo"

plugins:
  - jekyll-feed

defaults:
  -
    scope:
      path: ""
    values:
      layout: "page"
  -
    scope:
      path: "_posts"
    values:
      layout: "post"

