// # Olha só quem reverteu novamente para o Haredoc!
//
// É, desculpa por isso, eu tenho um problema.
//
// Enfim, não tem muita coisa para falar, só... sei lá cara, tava tudo certo com
// o Jekyll, tudo ocorrendo do jeito que eu gosto, eu fiz um puta de um post
// grande do cacete, fiz uma porrada de tema e já tô usando um bagulho limitado
// de novo.
//
// Sim, limitado.
//
// Isso aqui usa um markup beeeem simples. Simples ao ponto de que, como eu
// mesmo já comentei anteriormente ([[post_2025_04_22]]):
//
// | Então eu tomei a decisão lógica de pedir um snippet de código ao ChatGPT para que eu pudesse modificar elementos do HTML usando JavaScript.
//
// Modificações essas que me permitem gerar uma citação e ter um syntax
// highlighting para Hare nos blocos de código.
//
// Eu também não consigo:
//
// - deixar algo em negrito/itálico
// - fazer tabelas
// - adicionar uma divisória
// - fazer links com texto customizado
// - fazer listas ordenadas (por mais que eu nunca use)
// - adicionar imagens
//
// E é isso, todo o resto não tem como utilizar aqui, e ainda assim eu fiquei
// tentado a usar isso aqui de novo!
//
// # Arrggghhh! Eu sou o meu maior inimigo!
//
// Sabe a melhor parte? Só tem como saber do quê que eu tô falando se:
//
// - você viu o site antes de eu ter essa crise de idêntidade
// - você tem uma cópia do código-fonte dessa versão
//
// E no caso de ser a sua primeira vez aqui, ou no caso de você estar
// acompanhando esse blog pelo celular e não chegou a ver essa versão da qual eu
// estou falando, então não tem como entender nada do que eu estou falando.
//
// # Enfim
//
// Não são só desvantagens, tem coisas boas nessa simplicidade toda. Um exemplo
// disso é o tamanho do site e o desempenho dele. Como o site todo (após
// compilado) é composto por 5 arquivos (a página index e 404, o css, a fonte e
// o favicon), é difícil achar algo que não dê conta de carregar esse site.
//
// Tem JavaShit, mas é pouquíssimo e só roda na renderização da página, depois
// disso, não tem mais nada relacionado a isso em execução.
export fn post_2025_04_29() (etc, updates, web);
