// # Olha só que reverteu novamente para a Hare!
//
// É, desculpa por isso, eu tenho um problema.
//
// Enfim, não tem muita coisa para falar, só... sei lá cara, tava tudo certo com
// o Jekyll, tudo ocorrendo do jeito que eu gosto, eu fiz um puta de um post
// grande do cacete, fiz uma porrada de tema e já tô usando um bagulho limitado
// de novo.
//
// Sim, limitado.
//
// Isso aqui usa um markup beeeem simples. Simples ao ponto de que, como eu
// mesmo já comentei anteriormente ([[post_22_04_2025]]):
//
// | Então eu tomei a decisão lógica de pedir um snippet de código ao ChatGPT para que eu pudesse modificar elementos do HTML usando JavaScript.
//
// Modificações essas que me permitem gerar uma citação e ter um syntax
// highlighting para Hare nos blocos de código.
//
// Eu também não consigo:
//
// - deixar algo em negrito/itálico
// - fazer tabelas
// - adicionar uma divisória
// - fazer links com texto customizado
// - fazer listas ordenadas (por mais que eu nunca use)
// - adicionar imagens
//
// E é isso, todo o resto não tem como utilizar aqui, e ainda assim eu fiquei
// tentado a usar isso aqui de novo!
//
// # Arrggghhh! Eu sou o meu maior inimigo!
export fn post_29_04_2025() (etc, inconsistencia);
