#+TITLE: Haiku
#+DATE: <2024-03-01>
Que... nostalgia.

Após longos 3 anos, finalmente pude instalar o Haiku no meu PC novamente. Como eu estava com saudades desse sistema.

Esse carinha fez parte do meu início com sistemas alternativos para computador, uma "febre" que tive (e que tenho até hoje na realidade),

e também nesse período, se tornou o meu sistema favorito.

O Haiku me passa uma vibe tão tranquilizante que chega me assusta um pouco. Ele é quase um detox da computação moderna em alguns pontos,

por mais que isso não seja proposital, e eu gosto muito disso.

Ele vem com uma suíte de aplicações que são o suficiente para as minhas necessidades com computadores:

- Um editor de texto
- Um visualizador de PDF
- Um player multimídia
- Um gerenciador de arquivos rápido e simples de usar
- Um particionador de discos

E até mesmo outras coisas muito bacanas, como um cliente IRC, um editor de código simples e até mesmo um navegador de internet próprio.

Todos são ferramentas simples e que possuem um design coeso e amigável, é quase como se o sistema quisesse te manter em um
ambiente confortável para que você trabalhe tranquilamente.

Ah, é claro, esqueci de esclarecer uma coisa: Ele não é Linux, nem BSD, nem Unix, ele é um sistema feito do *zero*. 
