#+TITLE: Eu sem querer deletei o meu site do Neocities 💀
#+DATE: <2026-05-13 Wed>


Pois é, eu simplesmente deletei o meu site no Neocities. Bom… não exatamente.

O que aconteceu é que eu estava (estou) fazendo experimentos com o [[https://deno.com/deploy][Deno Deploy]],
[[https://lume.land/][Lume]] e [[https://lume.land/cms][LumeCMS]]. Só que tem um pequeno porém: Você precisa usar um repositório no
Github para poder usar o Deno Deploy.

Até aí, tudo bem, 0 problemas.

Mas, eu esqueci que no repositório do meu site no Github tinha um Github Action
configurado para “atualizar”/sobrescrever o site do meu Neocities. Isso porque
ele era um repositório com o código-fonte de uma versão antiga do meu site em
que eu usava [[https://jekyllrb.com/][Jekyll]].

É, eu fui muleque pra cacete.

Mas o lado bom é que eu já tinha uma versão funcional do meu site feita em Lume,
então em questão de conteúdo eu não perdi nada. Além disso, eu (acho que) tenho
um backup do site do Neocities relativamente atual. Só vou conseguir ter certeza
quando eu chegar em casa.  O site ainda não está 100%


Ainda faltam alguns ajustes e otimizações a serem feitas, afinal de contas eu
não estava planejando tacar uma bomba de hidrogênio num site que eu passei meses
desenvolvendo.



Para além disso, eu também não consegui replicar absolutamente tudo do meu site,
e tive que fazer algumas adaptações. Por exemplo, antes, cada livro da minha
lista de leitura tinha uma página própria, agora, alguns deles mostram uma
pequena janela com a minha opinião sobre ele (isso só funciona no desktop, por
enquanto).
