#+TITLE: Chrome Devtools
#+DATE: <2026-01-25 Sun>

Vem cá, desde quando os navegadores que a gente usa todo santo dia se tornaram uma IDE também?

Eu não tô brincando, se você tem um site escrito à mão (HTML, CSS e JS sem um processo de build, como em um SSG) você pode fazer esse teste:
- Abrir o site no navegador
- Apertar a tecla ~F12~
- Clicar em "Sources", depois Workspace
- "Add folder manually"
- Colocar a pasta do site, e... pronto, você tem uma IDE para editar o seu site. Sem precisar instalar mais nenhum programa externo.

#+begin_quote
**Detalhe**

No Chrome, você consegue até mesmo habilitar uma função similar ao Github Copilot!
#+end_quote

Isso é um treco que eu já havia visto anteriormente, mas não havia parado para pensar em quando isso ficou dessa forma. Sinceramente estou curioso para saber, mas não quero ter que me enfiar em um /Rabbit Hole/ só por conta de algo besta como esse.

Se você tem alguma noção de quando os navegadores ficaram assim, sinta-se à vontade para comentar na [[https://neocities.org/site/tukainpng][minha página do Neocities]].

Isso é melhor do que o VSCode, Vim ou Emacs? Não. Nem de longe. Não tem o mínimo de comparação. O editor de texto em si é bem simples, o que é "atraente" é todo o resto das ferramentas que tem por aqui.

Debugger, Análise de uso de memória/rede, monitor de performance, enfim, é uma IDE.

Se comparar com o editor do Neocities aí sim isso aqui se torna algo foderoso. Você tem basicamente aquele /Workflow/ de Ver, Editar, Ver de novo. Algo que você tem também no editor do Neocities, com a diferença sendo que você não está ativamente alterando o seu site que está no ar.

#+begin_quote
**Resumo da ópera**

Um site simples é infinitas vezes mais versátil do que qualquer outra coisa.
#+end_quote

A parte mais maneira desse /Workflow/ é que você pode literalmente selecionar qualquer elemento do site, e ficar modificando o CSS, e então, salvar o arquivo! Para um site em que o CSS é extremamente relevante (como esse) isso é uma /Killer Feature/.


