#+TITLE: Org-mode
#+DATE: <2025-05-26 seg>

O famoso Org-mode... Como que eu posso descrever...

* O maior trunfo do Emacs.
Acho que isso não é lá tão polêmico de dizer. O Emacs é capaz de muitas coisas, *muitas*, mas essa /coisinha/ em específico é tão incrível que até mesmo fura a bolha da comunidade do Emacs e chega à comunidades como a do Vim/Neovim.

Você pode comparar o org-mode com o sistema de organização que usa Markdown. Com a diferença que nesse sistema imaginário as partes provavelmente seriam programas diferentes um do outro, e no caso do org-mode, tá tudo dentro do Emacs, e tudo interage e é integrado com maestria.

Você consegue fazer planejamentos com uma agenda, distribuir tarefas entre diversos documentos, /deadlines/, exportação de documentos (que inclusive, é assim que esse site é gerado) entre diversas outras coisas.

Até mesmo planilhas você consegue fazer! Isso mesmo, planilhas, não tabelas (chupa essa manga, Markdown).

* Geração de sites
Como já mencionei, esse site em si é gerado a partir do org-mode, os detalhes de como isso funcionam são um pouco longos demais para que eu consiga explicar de forma rápida.

Mas basicamente é o seguinte:

- Dentro do org-mode, existe uma ferramenta de publicação.
- Você pode criar um "/script/" em =elisp= configurando um projeto
- Nesse /script/ você exporta o projeto em uma série de arquivos HTML

Isso não é toda a história, mas é o conceito base.

Enfim, essa ferramenta de publicação consegue transformar os seus documentos feitos em org-mode para uma variedade de outros formatos, como pdf's, LaTeX e etc.

Ainda por cima existe a possibilidade da lista de arquivos ser expandida por meio de pacotes externos, como por exemplo o [[https://melpa.org/#/ox-pandoc][ox-pandoc]], que te permite converter um documento =.org= para qualquer outro formato suportado pelo [[https://pandoc.org/][pandoc]] (é bastante, viu).

** Execução de código dentro do org-mode

Pois é, ele é capaz até mesmo disso!

Não sei como eu posso exemplificar isso aqui neste artigo, mas aqui vai um exemplo tirado do fundo dos meus 83 de QI:

Você tem um documento =.org= em que você está fazendo anotações sobre a linguagem de programação [[https://harelang.org][Hare]], e então você deixa anotado o exemplo de "/hello, world!/" que é exibido no site da Hare.

#+begin_src hare
use fmt;

export fn main() void = {
	const greetings = [
		"Hello, world!",
		"¡Hola Mundo!",
		"Γειά σου Κόσμε!",
		"Привіт, світе!",
		"こんにちは世界！",
	];
	for (let greeting .. greetings) {
		fmt::println(greeting)!;
	};
};
#+end_src

Você pode configurar o bloco de código para poder compilar e executar esse código, dentro do próprio org-mode!

Você precisaria de algo como

#+begin_src emacs-lisp
(org-babel-do-load-languages
 'org-babel-load-languages '((C . t)))
#+end_src

Presente na sua configuração do Emacs para que o org-mode saiba o que ele deve usar para compilar/executar esse block de código. Mas ainda assim, é muito maneiro saber que ele tem essa capacidade!

[[https://youtu.be/aiBt8CieE7U?si=j_vCLvhqtJUenLkO&t=373][Esse vídeo]] demonstra bem o que eu quero dizer.

* TODO Finalizar artigo
