#+TITLE: Um setup offline
#+DATE: <2025-07-10 qui>

A internet no Brasil é uma coisa... "interessante". Interessante na forma do quão cara ela é e também no quão não-confiável e lento o serviço é. E tanto no bom quanto no mau caso, um setup com uma instalação offline do Linux é a melhor opção que você pode ter. Principalmente se esse setup tiver todos os programasque você pode acabar precisando já pré-instalados ou disponíveis para instalação, mesmo sem conexão com a internet.

Algo que lembre as antigas distribuições Linux --- aquelas que vinham em um /bundle/ de CDs de instalação e de programas "extras", como o antigo Debian ou RedHat Linux.

Sim. Eu sou um nerd.

Enfim.

Eu já tenho comigo um setup que cumpre esses requisitos, e para dar aquela
temperada, ele também usa o tema [[https://github.com/grassmunk/Chicago95/][Chicago95]] para combinar com essa "estética retrô".

#+begin_quote
Só para ser claro, você não precisa ser um nerd como eu para ter um setup assim, na verdade eu recomendo esse tipo de setup para qualquer um. Depender demais no acesso livre à internet é algo que só tende a dar merda no futuro, então é bom ter um plano B.
#+end_quote

O meu setup em si é bem "simples" (pelo menos comparado ao tipo de coisa que você vê no [[https://www.reddit.com/r/unixporn/][unixporn]]). Ele usa o /desktop environment/ (eita nome xique) [[https://xfce.org/][XFCE]], tem alguns utilitários, programas básicos (bloco de notas, calculadora, esse tipo de coisa) e também algumas ferramentas de desenvolvedor como o [[https://geany.org][Geany]] e compiladores como o [[https://clang.llvm.org/][Clang]]. Todos os pacotes, bibliotecas e suas respectivas dependências estão guardados é um diretório do meu HD secundário e também no meu Pendrive.

Ao todo, tudo isso dá +/- uns 4.5Gb. Pois é, uma IDE, editores de vídeo e imagem, um navegador de internet, um pacote office completo, entre outras coisas, tudo isso somado é menor que o CoD Mobile.

Sendo assim, eu consigo fazer um clone do meu computador de forma extremamente fácil (bom, pelo menos mais fácil do que fazer uma instalação do Windows 11 sem internet), e também consigo utilizar o meu computador sem conexão alguma com a internet, mesmo que isso seja uma situação improvável de acontecer, levando em conta o mundo em que vivemos. Mas ter a segurança de que eu não preciso de internet para o meu computador funcionar/ser útil já é algo que me deixa satisfeito.

Experimenta usar um computador com a instalação base do Windows 11 sem internet, é tão útil quanto um [[https://www.google.com/intl/pt_br/chromebook/][Chromebook]] de 2015, e de alguma forma ele fica pior a partir do momento em que ele tem acesso a internet!

Eu tenho desde um bloco de notas à uma instalação do TeXLive ([[https://www.latex-project.org/][LaTeX]]).

Preciso fazer um TCC? Eu consigo de boa. Fazer uma apresentação de slides?
Tranquilo. Criar um site que lista documentos com base em um banco de dados simples? O [[https://jekyllrb.com/][Jekyll]] já tá pronto para usar.

#+begin_quote
Opa, pera aí, esse último foi um pouco específico demais 🤔
#+end_quote

Num saldo geral, eu consigo me virar até que bem se eu ficar sem acesso à
internet. E isso conta com o lazer também, já que eu tenho um Switch Lite (inclusive, vai tomar no cu, Nintendo! [[https://www.nintendo.com/pt-br/store/products/mario-kart-world-switch-2/][R$500 num jogo do Mario]]? É sério?).
