name: Publish on Github Pages and Neocities

on:
  push:
    branches: [main]

concurrency: # prevent concurrent deploys doing strange things
  group: deploy-to-neocities
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      pages: write
    steps:
        - name: Checkout
          uses: actions/checkout@v4
        - name: Setup Pages
          id: pages
          uses: actions/configure-pages@v5
        - name: Build with Jekyll
          run: sudo apt install jekyll && jekyll b
        - name: Upload artifact
          uses: actions/upload-pages-artifact@v3
        - name: Deploy to neocities
          uses: bcomnes/deploy-to-neocities@v3
          with:
            api_key: ${{ secrets.NEOCITIES_API_TOKEN }}
            cleanup: true
            neocities_supporter: false
            preview_before_deploy: false
            dist_dir: _site
