name: Publish on Github Pages and Neocities

on:
  push:
    branches: [main]

concurrency: # prevent concurrent deploys doing strange things
  group: deploy-to-neocities
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      pages: write
    steps:
        - name: Checkout
          uses: actions/checkout@v4
        - name: Setup Ruby
          # https://github.com/ruby/setup-ruby/releases/tag/v1.207.0
          uses: ruby/setup-ruby@4a9ddd6f338a97768b8006bf671dfbad383215f4
          with:
            ruby-version: '3.1' # Not needed with a .ruby-version file
            bundler-cache: true # runs 'bundle install' and caches installed gems automatically
            cache-version: 0 # Increment this number if you need to re-download cached gems
        - name: Setup Pages
          id: pages
          uses: actions/configure-pages@v5
        - name: Build with Jekyll
          # Outputs to the './_site' directory by default
          run: bundle exec jekyll build
          env:
            JEKYLL_ENV: production
        - name: Upload artifact
          # Automatically uploads an artifact from the './_site' directory by default
          uses: actions/upload-pages-artifact@v3
        - name: Deploy to neocities
          uses: bcomnes/deploy-to-neocities@v3
          with:
            api_key: ${{ secrets.NEOCITIES_API_TOKEN }}
            cleanup: true
            neocities_supporter: false
            preview_before_deploy: false
            dist_dir: _site
